config/routes.rb
Rails.application.routes.draw do
  resources :topicos do
  	resources :comentarios
  end
  
  devise_for :usuarios
  get 'front_page/index'
  get 'front_page/threads'
  get 'front_page/comments'
  get 'front_page/users'
  
  root 'front_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :topico
  belongs_to :usuario
end

app/models/topico.rb
class Topico < ApplicationRecord
	belongs_to :usuario
	has_many :comentarios, dependent: :destroy
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :topico, dependent: :destroy
  has_many :comentario, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({roles: []}, :email, :password) }
	end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:show]
  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    if usuario_signed_in?
    @comentario = Comentario.new
  end
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    if usuario_signed_in?
    @comentario = Comentario.new(comentario_params)
    respond_to do |format|
      if @comentario.save
        format.html { redirect_to topicos_path, notice: 'Comentario was successfully created.'}
        format.json { render :form}
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    if usuario_signed_in?
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to topicos_path, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    if usuario_signed_in?
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to redirect_to topicos_path, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:titulo, :corpo, :topico_id, :usuario_id)
    end
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  def index
  end
  def threads
  end
  def comments
  end
  def users
  	@Users = Usuario.all
  end
end

app/controllers/topicos_controller.rb
class TopicosController < ApplicationController
  before_action :set_topico, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index, :show]
  # GET /topicos
  # GET /topicos.json
  def index
    @topicos = Topico.all
  end

  # GET /topicos/1
  # GET /topicos/1.json
  def show
  end

  # GET /topicos/new
  def new
    if usuario_signed_in?
    @topico = current_usuario.topico.build
    end
  end

  # GET /topicos/1/edit
  def edit
  end

  # POST /topicos
  # POST /topicos.json
  def create
    if usuario_signed_in?
    @topico = current_usuario.topico.build(topico_params)

    respond_to do |format|
      if @topico.save
        format.html { redirect_to @topico, notice: 'Topico was successfully created.' }
        format.json { render :show, status: :created, location: @topico }
      else
        format.html { render :new }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # PATCH/PUT /topicos/1
  # PATCH/PUT /topicos/1.json
  def update
    if usuario_signed_in?
    respond_to do |format|
      if @topico.update(topico_params)
        format.html { redirect_to @topico, notice: 'Topico was successfully updated.' }
        format.json { render :show, status: :ok, location: @topico }
      else
        format.html { render :edit }
        format.json { render json: @topico.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /topicos/1
  # DELETE /topicos/1.json
  def destroy
    if usuario_signed_in?
    @topico.destroy
    respond_to do |format|
      format.html { redirect_to topicos_url, notice: 'Topico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topico
      @topico = Topico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topico_params
      params.require(:topico).permit(:titulo, :jogo, :genero, :corpo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentario_helper.rb
module ComentarioHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/topicos_helper.rb
module TopicosHelper
end

app/views/comentarios/_form.html.erb
<center><%= simple_form_for @comentario, url: {action: "create"}, html: {class: "comentario"} do |form| %>
<% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <%end%>
  <div class="field">
    <b>Titulo</b>
    <br>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <b>Texto</b>
    <br>
    <%= form.text_area :corpo, size: "50x6" %>
  </div>

  <div class="field">
    <%= form.input :usuario_id, :as => :hidden, :input_html => { :value => current_usuario.id } %>
  </div>

  <div class="field">
    <%= form.input :topico_id, :as => :hidden, :input_html => { :value => $page } %>
  </div>


  <div class="actions">
     <%= form.submit( class: "btn btn-outline-success") %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<center><h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %></center>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Corpo</th>
      <th>Topico</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.titulo %></td>
        <td><%= comentario.corpo %></td>
        <td><%= comentario.topico.titulo %></td>
        <td><%= comentario.usuario.email %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comentarios/new.html.erb
<%= render 'form', comentario: @comentario %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @comentario.titulo %>
</p>

<p>
  <strong>Corpo:</strong>
  <%= @comentario.corpo %>
</p>

<p>
  <strong>Topico:</strong>
  <%= @comentario.topico %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', topico_comentarios_path(@topico) %>

app/views/front_page/comments.html.erb
<center>
<h1>My Comments</h1>
<h1>____________</h1>

<% i = 0%>
<% current_usuario.comentario.each do |comentario|%>
	<% i+=1%>
<%end%>

<% if i != 0%>
	<% current_usuario.comentario.each do |comentario|%>
		<h3>Thread</h3>
		<h5><%= comentario.topico.titulo %></h5>
		<h5>_________________________</h5>
		<h5><%= comentario.titulo %></h5>
		<h7><%= comentario.corpo %></h7>
		<h5>________________________</h5>
	<% end %>
<%else%>
	<h3>You don't have any comments</h3>
	<center><a class="btn btn-outline-success" href="/topicos" role="button">Start Now</a></center>
<%end%>
</center>

app/views/front_page/index.html.erb
<center>
<% if usuario_signed_in? %>
	<h1>Bem Vindo</h1>
	<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Yes_Check_Circle.svg/1024px-Yes_Check_Circle.svg.png" width="350" height="350" class="d-inline-block align-center" alt="Perfil">
	<br>
	<br>
	<a class="btn btn-outline-success btn-lg" href="/usuarios/edit" role="button">Editar Perfil</a>
<% else %>
	<h1>NOT LOGGED IN YET</h1>
	<img src="https://emd-public.nyc3.digitaloceanspaces.com/eusouempreendedor-uploads/X.png" width="350" height="350" class="d-inline-block align-center" alt="Perfil">
<% end %>
<br>   
</center>

app/views/front_page/threads.html.erb
<center>
<h1>My Threads</h1>

<% i = 0%>
<% current_usuario.topico.each do |topico|%>
	<% i+=1%>
<%end%>

<% if i != 0%>
	<% current_usuario.topico.each do |topico|%>
		<h3>Title:</h3>
		<h4><%= topico.titulo %></h4>
		<%= link_to 'Ver mais', topico, :class => "btn btn-outline-info btn-sm" %>
	<% end %>
<%else%>
	<h3>You don't have any threads</h3>
	<center><a class="btn btn-outline-success" href="/topicos/new" role="button">Start Now</a></center>
<%end%>
</center>

app/views/front_page/users.html.erb
<center>
<h1>All Users</h1>


	<% @Users.each do |user|%>
		<h3>Email: </h3>
		<h5><%= user.email %></h5>
		<h5>_______________________________</h5>
	<% end %>
</center>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <img src="http://aux.iconspalace.com/uploads/gamehub-icon-256.png" width="40" height="40" class="d-inline-block align-center" alt="Logo">
    <span class="navbar-brand" href="#">GameHub</span>
    </span>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="http://localhost:3000">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/topicos">Threads</a>
      </li>
      <% if usuario_signed_in? %>
        <li class="nav-item">
         <a class="nav-link" href="/front_page/threads">My Threads</a>
        </li>
        <li class="nav-item">
         <a class="nav-link" href="/front_page/comments">My Comments</a>
        </li>
        <% if current_usuario.isAdmin? %>
          <li class="nav-item">
            <a class="nav-link" href="/front_page/users">Manage Users</a>
          </li>
        <% end %>
      <%end%>
    </ul>
    <% if usuario_signed_in? %>
        <%= link_to('Logout', destroy_usuario_session_path, method: :delete, :class => "btn btn-outline-danger btn-sm" ) %>
      <% else %>
        <a class="btn btn-outline-success" href="/usuarios/sign_in" role="button">Log In</a>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/topicos/_form.html.erb
<center><%= form_with(model: topico, local: true) do |form| %>
  <% if topico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topico.errors.count, "error") %> prohibited this topico from being saved:</h2>

      <ul>
      <% topico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>Title</b>
    <br>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <b>Game</b>
    <br>
    <%= form.text_field :jogo %>
  </div>

  <div class="field">
    <b>Genre</b>
    <br>
    <%= form.text_field :genero %>
  </div>

  <div class="field">
    <b>Text</b>
    <br>
    <%= form.text_area :corpo, size: "100x12" %>
  </div>

  <div class="actions">
    <%= form.submit( class: "btn btn-outline-success") %>
  </div>
<% end %>
</center>

app/views/topicos/edit.html.erb
<center><h1>Editing Thread</h1>
<%= render 'form', topico: @topico %>

<%= link_to 'Show', @topico %> |
<%= link_to 'Back', topicos_path %>
</center>

app/views/topicos/index.html.erb
<center><h1>Threads</h1></center>
 <center> <tbody>
    <h2>Titles:</h2>
    <% @topicos.each do |topico| %>
      <tr>
        <td>
        <h4><%= topico.titulo %> </h4>
        <br>
        <%= link_to 'Show More', topico, :class => "btn btn-outline-info btn-sm" %>
        <br>
        <h4>_____________________________________________________________</h4>
        <br>
        <br>
      </tr>
    <% end %>
  </tbody></center>

<br>
<br>
<br>

<% if usuario_signed_in? %>
<center><a class="btn btn-outline-success" href="/topicos/new" role="button">New Thread</a></center>
<% end %>

app/views/topicos/new.html.erb
<center><h1>New Thread</h1>
<%= render 'form', topico: @topico %>
<br>
<a class="btn btn-outline-primary" href="/topicos" role="button">Back</a></center>

app/views/topicos/show.html.erb
<center><p id="notice"><%= notice %></p>
<% $page = @topico.id%>

<p>
  <h1>Title:
    <% if usuario_signed_in? %>
    <% if @topico.usuario.id == current_usuario.id || current_usuario.isAdmin? %> <%= link_to 'Edit', edit_topico_path(@topico), :class => "btn btn-outline-success btn-sm" %>  <%= link_to 'Delete', @topico, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-danger btn-sm"%><%end%>
    <%end%>
    <%= link_to 'Back', topicos_path, :class => "btn btn-outline-primary btn-sm"%></h1>
    <h3><%= @topico.titulo %></h3>
</p>

<p>
  <strong>Game:</strong>
  <br>
  <%= @topico.jogo %>
</p>

<p>
  <strong>Genre:</strong>
  <br>
  <%= @topico.genero %>
</p>

<p>
  <strong>Post:</strong>
  <br>
  <%= @topico.corpo %>
</p>
 <% if usuario_signed_in? %>
<h1>Comments  <%= link_to 'Comment', new_topico_comentario_path(@topico), :class => "btn btn-outline-success btn-sm" %></h1>
<% end %>
<% @topico.comentarios.each do |comment| %>
  <h6>User:
    <%= comment.usuario.email %>
    </h6>
	<%= comment.titulo %>
  <br>
  <h7>_____________</h7>
  <br>
  <%= comment.corpo %>
	<br>
  <br><br>
<%end%>
</center>